### ISSUE TITLE
TypeError: Unsupported type of data <class 'str'>

### ISSUE THREAD

**Issue by ysrdcm** [ChelsieLei/EZ-HOI#2]
Hi, thank you for your excellent work！

I am having the following problems with the reproduction process, can you offer me some advice?

`Traceback (most recent call last):
  File "main_tip_finetune.py", line 740, in <module>
    main(0,args)
  File "main_tip_finetune.py", line 490, in main
    engine(args.epochs)
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/core/distributed.py", line 136, in __call__
    self._on_start_iteration()
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/core/distributed.py", line 173, in _on_start_iteration
    self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True)
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/ops/relocate.py", line 63, in relocate_to_cuda
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/ops/relocate.py", line 63, in <listcomp>
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/ops/relocate.py", line 68, in relocate_to_cuda
    x[key] = relocate_to_cuda(x[key], ignore, device, **kwargs)
  File "/home/shurong/miniconda3/envs/myenv/pocket/pocket/ops/relocate.py", line 73, in relocate_to_cuda
    raise TypeError('Unsupported type of data {}'.format(type(x)))
TypeError: Unsupported type of data <class 'str'>`

**Comment by ChelsieLei** [comment]
Thanks for your interest in our work. 

I think you need to edit the function "_on_start_iteration()" of the class "DistributedLearningEngine" in the file "/home/shurong/miniconda3/envs/myenv/pocket/pocket/core/distributed.py" as follows:

```
    def _on_start_iteration(self):
        self._state.iteration += 1
        self._state.inputs = relocate_to_cuda(self._state.inputs, non_blocking=True)
     
        file = [tgt['filename'] for tgt in self._state.targets]
        self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True)
        for idx, tgti in enumerate(self._state.targets):
            self._state.targets[idx]['filename'] = (file[idx])
```

**Comment by SiriusL1** [comment]
根据您给出的解决方案添加功能，仍然报告了

**Comment by leo7x1n** [comment]
Adding the function according to the solution you gave still reported an error.

**Comment by leo7x1n** [comment]
`Traceback (most recent call last):
  File "/root/autodl-tmp/workspace/ez/main_tip_finetune.py", line 740, in <module>
    mp.spawn(main, nprocs=args.world_size, args=(args,))
  File "/root/miniconda3/envs/ez/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/ez/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/ez/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ez/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/workspace/ez/main_tip_finetune.py", line 488, in main
    engine(args.epochs)
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/core/distributed.py", line 136, in __call__
    self._on_start_iteration()
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/core/distributed.py", line 173, in _on_start_iteration
    self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True)
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/ops/relocate.py", line 63, in relocate_to_cuda
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/ops/relocate.py", line 63, in <listcomp>
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/ops/relocate.py", line 68, in relocate_to_cuda
    x[key] = relocate_to_cuda(x[key], ignore, device, **kwargs)
  File "/root/autodl-tmp/workspace/ez/pocket/pocket/ops/relocate.py", line 71, in relocate_to_cuda
    raise TypeError('Unsupported type of data {}'.format(type(x)))
TypeError: Unsupported type of data <class 'str'>
`

**Comment by ChelsieLei** [comment]
The original code runs correctly on my device, but I suspect the issue is related to the `filename` key in the `self._state.targets` dictionary. Since `filename` contains string data, it may cause issues when relocating the dictionary to CUDA. 
You can check again which keys in the `self._state.targets` dictionary contain string data.
A possible solution is to remove the `filename` key before calling the `relocate_to_cuda` function, ensuring only compatible data types are processed.
```python
self._state.targets.pop("filename", None)  
self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True)
```

**Comment by SiriusL1** [comment]
```
[{'boxes_h': tensor([], size=(0, 4)), 'boxes_o': tensor([], size=(0, 4)), 'hoi': tensor([495]), 'object': tensor([], dtype=torch.int64), 'verb': tensor([44]), 'orig_size': tensor([640, 427]), 'labels': tensor([], dtype=torch.int64), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00013651.jpg'}, {'boxes_h': tensor([[0.1773, 0.6159, 0.0547, 0.2763],
        [0.2336, 0.6171, 0.0922, 0.3255],
        [0.7953, 0.6417, 0.0750, 0.4028],
        [0.9195, 0.5878, 0.0859, 0.3560],
        [0.6719, 0.6885, 0.0969, 0.4356]]), 'boxes_o': tensor([[0.1992, 0.4438, 0.0609, 0.3443],
        [0.2828, 0.4637, 0.0688, 0.4169],
        [0.7164, 0.3396, 0.1172, 0.5808],
        [0.8734, 0.4778, 0.1031, 0.5386],
        [0.7164, 0.3396, 0.1172, 0.5808]]), 'hoi': tensor([518, 518, 518, 518, 518]), 'object': tensor([37, 37, 37, 37, 37]), 'verb': tensor([36, 36, 36, 36, 36]), 'orig_size': tensor([427, 640]), 'labels': tensor([36, 36, 36, 36, 36]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00006171.jpg'}, {'boxes_h': tensor([[0.1080, 0.4742, 0.2128, 0.7328],
        [0.8599, 0.4430, 0.2801, 0.7141],
        [0.6095, 0.4844, 0.2770, 0.7812],
        [0.3419, 0.5141, 0.2989, 0.7906]]), 'boxes_o': tensor([[0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266]]), 'hoi': tensor([245, 245, 245, 245]), 'object': tensor([13, 13, 13, 13]), 'verb': tensor([87, 87, 87, 87]), 'orig_size': tensor([640, 639]), 'labels': tensor([87, 87, 87, 87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00020581.jpg'}, {'boxes_h': tensor([[0.5000, 0.5000, 1.0000, 1.0000]]), 'boxes_o': tensor([[0.9923, 0.6027, 0.0155, 0.7946]]), 'hoi': tensor([29]), 'object': tensor([14]), 'verb': tensor([112]), 'orig_size': tensor([427, 640]), 'labels': tensor([112]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016155.jpg'}, {'boxes_h': tensor([[0.8590, 0.5020, 0.2820, 0.9960],
        [0.8816, 0.4993, 0.2367, 0.9986]]), 'boxes_o': tensor([[0.4889, 0.7293, 0.4902, 0.5413],
        [0.5022, 0.7322, 0.5115, 0.5357]]), 'hoi': tensor([377, 380]), 'object': tensor([43, 43]), 'verb': tensor([ 36, 115]), 'orig_size': tensor([360, 640]), 'labels': tensor([ 36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00031192.jpg'}, {'boxes_h': tensor([[0.2763, 0.4203, 0.1938, 0.3000]]), 'boxes_o': tensor([[0.4567, 0.4789, 0.9093, 0.8953]]), 'hoi': tensor([89]), 'object': tensor([56]), 'verb': tensor([87]), 'orig_size': tensor([640, 485]), 'labels': tensor([87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00012736.jpg'}, {'boxes_h': tensor([[0.5156, 0.5547, 0.1979, 0.2562]]), 'boxes_o': tensor([[0.4823, 0.4586, 0.7646, 0.7859]]), 'hoi': tensor([571]), 'object': tensor([7]), 'verb': tensor([75]), 'orig_size': tensor([640, 480]), 'labels': tensor([75]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00010919.jpg'}, {'boxes_h': tensor([[0.6750, 0.3381, 0.1844, 0.1862],
        [0.6844, 0.3431, 0.1156, 0.1640]]), 'boxes_o': tensor([[0.7273, 0.3957, 0.1984, 0.1761],
        [0.7250, 0.3927, 0.1750, 0.1660]]), 'hoi': tensor([478, 480]), 'object': tensor([31, 31]), 'verb': tensor([43, 93]), 'orig_size': tensor([494, 640]), 'labels': tensor([43, 93]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00026816.jpg'}, {'boxes_h': tensor([[0.3438, 0.8344, 0.0781, 0.2896],
        [0.3430, 0.8292, 0.0797, 0.2833]]), 'boxes_o': tensor([[0.3180, 0.7135, 0.0297, 0.0979],
        [0.3156, 0.7104, 0.0219, 0.0708]]), 'hoi': tensor([226, 230]), 'object': tensor([34, 34]), 'verb': tensor([ 36, 115]), 'orig_size': tensor([480, 640]), 'labels': tensor([ 36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00029895.jpg'}, {'boxes_h': tensor([[0.5000, 0.5000, 1.0000, 1.0000],
        [0.5000, 0.5000, 1.0000, 1.0000]]), 'boxes_o': tensor([[0.9785, 0.4615, 0.0430, 0.9230],
        [0.9239, 0.4671, 0.1521, 0.9342]]), 'hoi': tensor([330, 331]), 'object': tensor([42, 42]), 'verb': tensor([36, 50]), 'orig_size': tensor([480, 640]), 'labels': tensor([36, 50]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00009932.jpg'}, {'boxes_h': tensor([[0.2809, 0.5445, 0.5320, 0.8883]]), 'boxes_o': tensor([[0.1566, 0.6784, 0.3132, 0.5969]]), 'hoi': tensor([208]), 'object': tensor([24]), 'verb': tensor([8]), 'orig_size': tensor([432, 640]), 'labels': tensor([8]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016832.jpg'}, {'boxes_h': tensor([[0.6102, 0.6188, 0.7703, 0.6417],
        [0.6125, 0.6167, 0.7656, 0.6292]]), 'boxes_o': tensor([[0.5281, 0.6104, 0.9344, 0.7708],
        [0.5227, 0.5927, 0.9359, 0.8021]]), 'hoi': tensor([93, 94]), 'object': tensor([57, 57]), 'verb': tensor([49, 87]), 'orig_size': tensor([480, 640]), 'labels': tensor([49, 87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00035096.jpg'}, {'boxes_h': tensor([[0.5691, 0.4616, 0.5656, 0.8355]]), 'boxes_o': tensor([[0.2966, 0.2113, 0.0953, 0.1160]]), 'hoi': tensor([434]), 'object': tensor([65]), 'verb': tensor([36]), 'orig_size': tensor([480, 640]), 'labels': tensor([36]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016343.jpg'}, {'boxes_h': tensor([[0.6117, 0.5843, 0.1172, 0.3208]]), 'boxes_o': tensor([[0.6516, 0.4988, 0.3500, 0.4824]]), 'hoi': tensor([241]), 'object': tensor([59]), 'verb': tensor([87]), 'orig_size': tensor([427, 640]), 'labels': tensor([87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00035017.jpg'}, {'boxes_h': tensor([[0.4453, 0.4458, 0.0688, 0.2375],
        [0.2758, 0.4698, 0.1172, 0.3354],
        [0.2812, 0.4927, 0.1094, 0.2688]]), 'boxes_o': tensor([[0.5031, 0.3917, 0.0688, 0.0292],
        [0.3000, 0.3719, 0.0312, 0.1229],
        [0.3055, 0.3698, 0.0328, 0.1146]]), 'hoi': tensor([226, 226, 230]), 'object': tensor([34, 34, 34]), 'verb': tensor([ 36,  36, 115]), 'orig_size': tensor([480, 640]), 'labels': tensor([ 36,  36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016537.jpg'}, {'boxes_h': tensor([[0.8031, 0.6354, 0.3844, 0.6417],
        [0.2578, 0.6625, 0.3937, 0.6625],
        [0.6266, 0.4073, 0.1156, 0.2813],
        [0.1227, 0.4219, 0.1172, 0.3063],
        [0.7203, 0.4292, 0.1656, 0.2917],
        [0.3633, 0.4052, 0.1859, 0.2729],
        [0.0500, 0.6323, 0.1000, 0.6271],
        [0.8273, 0.5896, 0.3047, 0.2458],
        [0.7688, 0.6625, 0.4469, 0.6542],
        [0.2711, 0.6667, 0.4453, 0.6583]]), 'boxes_o': tensor([[0.4961, 0.6594, 0.6516, 0.5479],
        [0.4961, 0.6594, 0.6516, 0.5479],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250]]), 'hoi': tensor([108, 108, 109, 109, 109, 109, 109, 109, 109, 109]), 'object': tensor([60, 60, 60, 60, 60, 60, 60, 60, 60, 60]), 'verb': tensor([24, 24, 86, 86, 86, 86, 86, 86, 86, 86]), 'orig_size': tensor([480, 640]), 'labels': tensor([24, 24, 86, 86, 86, 86, 86, 86, 86, 86]), 'size': tensor([224, 224]), 'filename': 'HICO_train201

> 5_00000902.jpg'}]
> ```

**Comment by leo7x1n** [comment]
Thank you for your reply.Happy new year! 
This is the content of self._state.targets that I printed.
```
[{'boxes_h': tensor([], size=(0, 4)), 'boxes_o': tensor([], size=(0, 4)), 'hoi': tensor([495]), 'object': tensor([], dtype=torch.int64), 'verb': tensor([44]), 'orig_size': tensor([640, 427]), 'labels': tensor([], dtype=torch.int64), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00013651.jpg'}, {'boxes_h': tensor([[0.1773, 0.6159, 0.0547, 0.2763],
        [0.2336, 0.6171, 0.0922, 0.3255],
        [0.7953, 0.6417, 0.0750, 0.4028],
        [0.9195, 0.5878, 0.0859, 0.3560],
        [0.6719, 0.6885, 0.0969, 0.4356]]), 'boxes_o': tensor([[0.1992, 0.4438, 0.0609, 0.3443],
        [0.2828, 0.4637, 0.0688, 0.4169],
        [0.7164, 0.3396, 0.1172, 0.5808],
        [0.8734, 0.4778, 0.1031, 0.5386],
        [0.7164, 0.3396, 0.1172, 0.5808]]), 'hoi': tensor([518, 518, 518, 518, 518]), 'object': tensor([37, 37, 37, 37, 37]), 'verb': tensor([36, 36, 36, 36, 36]), 'orig_size': tensor([427, 640]), 'labels': tensor([36, 36, 36, 36, 36]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00006171.jpg'}, {'boxes_h': tensor([[0.1080, 0.4742, 0.2128, 0.7328],
        [0.8599, 0.4430, 0.2801, 0.7141],
        [0.6095, 0.4844, 0.2770, 0.7812],
        [0.3419, 0.5141, 0.2989, 0.7906]]), 'boxes_o': tensor([[0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266],
        [0.5016, 0.5898, 0.9969, 0.3266]]), 'hoi': tensor([245, 245, 245, 245]), 'object': tensor([13, 13, 13, 13]), 'verb': tensor([87, 87, 87, 87]), 'orig_size': tensor([640, 639]), 'labels': tensor([87, 87, 87, 87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00020581.jpg'}, {'boxes_h': tensor([[0.5000, 0.5000, 1.0000, 1.0000]]), 'boxes_o': tensor([[0.9923, 0.6027, 0.0155, 0.7946]]), 'hoi': tensor([29]), 'object': tensor([14]), 'verb': tensor([112]), 'orig_size': tensor([427, 640]), 'labels': tensor([112]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016155.jpg'}, {'boxes_h': tensor([[0.8590, 0.5020, 0.2820, 0.9960],
        [0.8816, 0.4993, 0.2367, 0.9986]]), 'boxes_o': tensor([[0.4889, 0.7293, 0.4902, 0.5413],
        [0.5022, 0.7322, 0.5115, 0.5357]]), 'hoi': tensor([377, 380]), 'object': tensor([43, 43]), 'verb': tensor([ 36, 115]), 'orig_size': tensor([360, 640]), 'labels': tensor([ 36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00031192.jpg'}, {'boxes_h': tensor([[0.2763, 0.4203, 0.1938, 0.3000]]), 'boxes_o': tensor([[0.4567, 0.4789, 0.9093, 0.8953]]), 'hoi': tensor([89]), 'object': tensor([56]), 'verb': tensor([87]), 'orig_size': tensor([640, 485]), 'labels': tensor([87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00012736.jpg'}, {'boxes_h': tensor([[0.5156, 0.5547, 0.1979, 0.2562]]), 'boxes_o': tensor([[0.4823, 0.4586, 0.7646, 0.7859]]), 'hoi': tensor([571]), 'object': tensor([7]), 'verb': tensor([75]), 'orig_size': tensor([640, 480]), 'labels': tensor([75]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00010919.jpg'}, {'boxes_h': tensor([[0.6750, 0.3381, 0.1844, 0.1862],
        [0.6844, 0.3431, 0.1156, 0.1640]]), 'boxes_o': tensor([[0.7273, 0.3957, 0.1984, 0.1761],
        [0.7250, 0.3927, 0.1750, 0.1660]]), 'hoi': tensor([478, 480]), 'object': tensor([31, 31]), 'verb': tensor([43, 93]), 'orig_size': tensor([494, 640]), 'labels': tensor([43, 93]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00026816.jpg'}, {'boxes_h': tensor([[0.3438, 0.8344, 0.0781, 0.2896],
        [0.3430, 0.8292, 0.0797, 0.2833]]), 'boxes_o': tensor([[0.3180, 0.7135, 0.0297, 0.0979],
        [0.3156, 0.7104, 0.0219, 0.0708]]), 'hoi': tensor([226, 230]), 'object': tensor([34, 34]), 'verb': tensor([ 36, 115]), 'orig_size': tensor([480, 640]), 'labels': tensor([ 36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00029895.jpg'}, {'boxes_h': tensor([[0.5000, 0.5000, 1.0000, 1.0000],
        [0.5000, 0.5000, 1.0000, 1.0000]]), 'boxes_o': tensor([[0.9785, 0.4615, 0.0430, 0.9230],
        [0.9239, 0.4671, 0.1521, 0.9342]]), 'hoi': tensor([330, 331]), 'object': tensor([42, 42]), 'verb': tensor([36, 50]), 'orig_size': tensor([480, 640]), 'labels': tensor([36, 50]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00009932.jpg'}, {'boxes_h': tensor([[0.2809, 0.5445, 0.5320, 0.8883]]), 'boxes_o': tensor([[0.1566, 0.6784, 0.3132, 0.5969]]), 'hoi': tensor([208]), 'object': tensor([24]), 'verb': tensor([8]), 'orig_size': tensor([432, 640]), 'labels': tensor([8]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016832.jpg'}, {'boxes_h': tensor([[0.6102, 0.6188, 0.7703, 0.6417],
        [0.6125, 0.6167, 0.7656, 0.6292]]), 'boxes_o': tensor([[0.5281, 0.6104, 0.9344, 0.7708],
        [0.5227, 0.5927, 0.9359, 0.8021]]), 'hoi': tensor([93, 94]), 'object': tensor([57, 57]), 'verb': tensor([49, 87]), 'orig_size': tensor([480, 640]), 'labels': tensor([49, 87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00035096.jpg'}, {'boxes_h': tensor([[0.5691, 0.4616, 0.5656, 0.8355]]), 'boxes_o': tensor([[0.2966, 0.2113, 0.0953, 0.1160]]), 'hoi': tensor([434]), 'object': tensor([65]), 'verb': tensor([36]), 'orig_size': tensor([480, 640]), 'labels': tensor([36]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016343.jpg'}, {'boxes_h': tensor([[0.6117, 0.5843, 0.1172, 0.3208]]), 'boxes_o': tensor([[0.6516, 0.4988, 0.3500, 0.4824]]), 'hoi': tensor([241]), 'object': tensor([59]), 'verb': tensor([87]), 'orig_size': tensor([427, 640]), 'labels': tensor([87]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00035017.jpg'}, {'boxes_h': tensor([[0.4453, 0.4458, 0.0688, 0.2375],
        [0.2758, 0.4698, 0.1172, 0.3354],
        [0.2812, 0.4927, 0.1094, 0.2688]]), 'boxes_o': tensor([[0.5031, 0.3917, 0.0688, 0.0292],
        [0.3000, 0.3719, 0.0312, 0.1229],
        [0.3055, 0.3698, 0.0328, 0.1146]]), 'hoi': tensor([226, 226, 230]), 'object': tensor([34, 34, 34]), 'verb': tensor([ 36,  36, 115]), 'orig_size': tensor([480, 640]), 'labels': tensor([ 36,  36, 115]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00016537.jpg'}, {'boxes_h': tensor([[0.8031, 0.6354, 0.3844, 0.6417],
        [0.2578, 0.6625, 0.3937, 0.6625],
        [0.6266, 0.4073, 0.1156, 0.2813],
        [0.1227, 0.4219, 0.1172, 0.3063],
        [0.7203, 0.4292, 0.1656, 0.2917],
        [0.3633, 0.4052, 0.1859, 0.2729],
        [0.0500, 0.6323, 0.1000, 0.6271],
        [0.8273, 0.5896, 0.3047, 0.2458],
        [0.7688, 0.6625, 0.4469, 0.6542],
        [0.2711, 0.6667, 0.4453, 0.6583]]), 'boxes_o': tensor([[0.4961, 0.6594, 0.6516, 0.5479],
        [0.4961, 0.6594, 0.6516, 0.5479],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250],
        [0.5266, 0.7333, 0.6031, 0.5250]]), 'hoi': tensor([108, 108, 109, 109, 109, 109, 109, 109, 109, 109]), 'object': tensor([60, 60, 60, 60, 60, 60, 60, 60, 60, 60]), 'verb': tensor([24, 24, 86, 86, 86, 86, 86, 86, 86, 86]), 'orig_size': tensor([480, 640]), 'labels': tensor([24, 24, 86, 86, 86, 86, 86, 86, 86, 86]), 'size': tensor([224, 224]), 'filename': 'HICO_train2015_00000902.jpg'}]
```
The following code can solve the error，but 
**I don't know if deleting the 'filename' will have an impact on training?**

```
def _on_start_iteration(self):
    # Increment the iteration count
    self._state.iteration += 1
    # Move input data to the CUDA device in non-blocking mode
    self._state.inputs = relocate_to_cuda(self._state.inputs, non_blocking=True)
    
    # Extract the 'filename' field and save it
    file = [tgt.pop('filename', None) for tgt in self._state.targets]
    
    # Move targets to CUDA, ignoring non-Tensor types of data
    self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True, ignore=True)
    
    # Re-assign the 'filename' field
    for idx, tgti in enumerate(self._state.targets):
        # Ensure 'filename' exists
        if file[idx] is not None:
            self._state.targets[idx]['filename'] = file[idx]
```

**Comment by ChelsieLei** [comment]
Happy new year!
The code should work without any issues. From the provided code, the `filename` information is stored in `file`. Before calling the `relocate_to_cuda` function, the `filename` key is removed to ensure only compatible data types are processed. Afterward, re-assign the `filename` information back into `self._state.targets`. You can give this approach a try. The string data doesn't need to be put into the cuda devices anyway.

**Comment by ChelsieLei** [comment]
I closed the issue. If you have any further questions, you can re-open it. Thanks.
